### ISSUE TITLE
Vein mining with "Building Wands" wands

### ISSUE THREAD

**Issue by Ben-Bingham** [TheStaticVoid/StaTech-Industry#425]
By using the Wands from the Building Wands mod you can easily vein mine any block, and keep the resource it drops. I have tested this with a diamond wand and a diamond pickaxe only, but from what I can tell this is an intended feature of the mod, and should probably be dealt with as it makes it way easier to mine ore veins. 

Steps to reproduce:

1. Get a Diamond Wand (from Building Wands), a diamond pickaxe and some blocks you wish to vein mine.
2. Rebind the key for the Building Wands "Wand Menu" to a non conflicting key.
3. Open the Wand Menu and set "Action" to Destroy, and set "Mode" to vein.
4. Click the button marked "Tools" and than place your pickaxe in the wands inventory.
5. Close the Wand Menu and simply right click any block you wish to vein mine.

Once again to reinstate this does seem like an intended feature of the mod and not a bug at all.

**Comment by TheStaticVoid** [comment]
This is known. The mod dev was supposed to fix the config setting that allowed you to disable this feature, but that never happened. For now, it's up to you if you want to use it. The public server has the mod removed because I feel it's honestly broken, but for people in singleplayer / private servers I leave the decision up to them.

**Comment by Ben-Bingham** [comment]
That makes sense, thanks.
